{% set version = "0.0.1" %}

package:
  name: gymnasium-notices
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gymnasium-notices/gymnasium-notices-{{ version }}.tar.gz
  sha256: 3e8c868046f56dea84c949cc7e97383cccfab27152fc3f4968754e4c9c087ab9

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - gymnasium_notices
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Farama-Foundation/gym-notices
  summary: Notices for gymnasium
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    Notices for gymnasium
  dev_url: https://github.com/Farama-Foundation/gym-notices
  doc_url: https://github.com/Farama-Foundation/gym-notices

extra:
  recipe-maintainers:
    - thewchan
    - conda-forge/gymnasium
